pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "ymore23/backend"
        FRONTEND_IMAGE = "ymore23/frontend"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/yashmore-23/goal-tracker.git'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t $BACKEND_IMAGE -f docker/backend.Dockerfile .'
                sh 'docker build -t $FRONTEND_IMAGE -f docker/frontend.Dockerfile .'
            }
        }

        stage('Push Images') {
            steps {
                withCredentials([usernamePassword(credentialsId: '186a4a99-e830-4eb3-98fb-4485d8ea5ebf', usernameVariable: 'Username', passwordVariable: 'Password')]) {
                    sh 'docker login -u ${env.Username} -p ${env.Password}'
                    sh 'docker push $BACKEND_IMAGE'
                    sh 'docker push $FRONTEND_IMAGE'
                }
            }
        }

        stage('Apply K8s') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}

