- hosts: local
  become: true
  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Kubernetes tools (kubectl, etc.)
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl && mv kubectl /usr/local/bin/

